# Задание 8 (финальное)

В этом задании Вам предлагается сделать несколько несложных упражнений с упомянутыми на лекции библиотеками, а также потренироваться использовать документацию к новым для Вас библиотекам, чтобы почувствовать, что теперь Вы сами можете продолжить свое знакомство с Питоном, осваивая новые инструменты.

## 1. Базовый уровень: задание по numpy и scipy

1. Напишите свой аналог np.linspace с использованием цикла и с использованием list comprehension. Сравните все три варианта по производительности
1. Сравните по производительности основные операции с массивами (array) numpy и с list
1. Попробуйте поменять метод оптимизации в примере решения оптимизационной задачи с помощью scipy.optimize, показанном на лекции (для этого потребуется обратиться к документации). Подберите метод с наименьшим количеством вычислений функции. Начальное приближение (точку [5,5]) оставьте тем же.

### Выполнение 1. пункт 1.

In [1]:
import numpy as np

In [2]:
np.linspace (2.0, 3.0, num = 5, endpoint=False)

array([ 2. ,  2.2,  2.4,  2.6,  2.8])

In [3]:
# аналог linspace с циклом for, но без параметра retstep 
def linspace_for(start_p, end_p, num=50, endpoint=True):
    if endpoint == False:
        step = (float(end_p) - start_p)/num
    else:
        step = (float(end_p) - start_p)/(num - 1)
    result = []
    elem = start_p
    for i in range(0,num,1):
        result.append(round(elem,8))
        elem += step
    return result

In [4]:
linspace_for(2.0, 3.0, num = 5, endpoint=False)

[2.0, 2.2, 2.4, 2.6, 2.8]

In [5]:
# аналог linspace с циклом list comprehension, но без параметра retstep 
def linspace_list_comprehension(start_p, end_p, num=50, endpoint=True):
    if endpoint == False:
        step = (float(end_p) - start_p)/num
    else:
        step = (float(end_p) - start_p)/(num - 1)
    elem = start_p    
    return [i*step+elem for i in range(0,num,1)]

In [6]:
linspace_list_comprehension(2.0, 3.0, num = 5, endpoint=False)

[2.0, 2.2, 2.4, 2.6, 2.8]

In [7]:
%timeit np.linspace(0, 10000)
%timeit linspace_for(0, 10000)
%timeit linspace_list_comprehension(0, 10000)

The slowest run took 8.23 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.65 µs per loop
10000 loops, best of 3: 48.2 µs per loop
100000 loops, best of 3: 5.65 µs per loop


In [8]:
%timeit np.linspace(0, 50, num=1000)
%timeit linspace_for(0, 50, num=1000)
%timeit linspace_list_comprehension(0, 50, num=1000)

The slowest run took 9.81 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.99 µs per loop
1000 loops, best of 3: 923 µs per loop
10000 loops, best of 3: 93.1 µs per loop


In [9]:
%timeit np.linspace(0, 50, num=5)
%timeit linspace_for(0, 50, num=5)
%timeit linspace_list_comprehension(0, 50, num=5)

The slowest run took 8.09 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.29 µs per loop
100000 loops, best of 3: 3.55 µs per loop
The slowest run took 4.00 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.28 µs per loop


### Выполнение 1. пункт 2.

In [10]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)

c = [20, 30, 40, 50]
d = [i for i in xrange(4)]

print a, b
print c, d

[20 30 40 50] [0 1 2 3]
[20, 30, 40, 50] [0, 1, 2, 3]


In [11]:
%timeit a + b
%timeit c + d

# сравним полученные значения
print a + b
print c + d

The slowest run took 42.96 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 395 ns per loop
The slowest run took 9.36 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 126 ns per loop
[20 31 42 53]
[20, 30, 40, 50, 0, 1, 2, 3]


#### Для list: c - d, c * d, c / d, c ** d, c % d - отрабатывает с ошибкой, т.е. нужно решать не стандартными методами

In [12]:
%timeit a - b
print a - b

The slowest run took 28.40 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 403 ns per loop
[20 29 38 47]


In [13]:
%timeit a * b
print a * b

The slowest run took 32.61 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 412 ns per loop
[  0  30  80 150]


In [14]:
# При делении на 0 возвращается inf (бесконечность)
%timeit a / b
print a / b

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel\__main__.py:257: RuntimeWarning: divide by zero encountered in divide


The slowest run took 222.52 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.06 µs per loop
[ 0 30 20 16]


C:\ProgramData\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in divide
  app.launch_new_instance()


In [15]:
%timeit a ** b
print a ** b

The slowest run took 32.66 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 737 ns per loop
[     1     30   1600 125000]


In [16]:
# При взятии остатка от деления на 0 возвращается 0
%timeit a % b
print a % b

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel\__main__.py:257: RuntimeWarning: divide by zero encountered in remainder


The slowest run took 44.63 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.06 µs per loop
[0 0 0 2]


C:\ProgramData\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in remainder
  app.launch_new_instance()


### Выполнение 1. пункт 3.

In [17]:
from scipy import optimize

In [18]:
def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

print f([3.2, 0.1])

3.0


In [19]:
x_min = optimize.minimize(f, [5, 5])
print x_min

      fun: 3.0000000000011435
 hess_inv: array([[ 0.94055055, -0.16183475],
       [-0.16183475,  0.55944947]])
      jac: array([ -2.05636024e-06,   5.36441803e-07])
  message: 'Optimization terminated successfully.'
     nfev: 16
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([ 3.19999896,  0.10000026])


#### method для optimize.minimize
        - 'Nelder-Mead' :ref:`(see here) <optimize.minimize-neldermead>`
        - 'Powell'      :ref:`(see here) <optimize.minimize-powell>`
        - 'CG'          :ref:`(see here) <optimize.minimize-cg>`
        - 'BFGS'        :ref:`(see here) <optimize.minimize-bfgs>`
        - 'Newton-CG'   :ref:`(see here) <optimize.minimize-newtoncg>`
        - 'L-BFGS-B'    :ref:`(see here) <optimize.minimize-lbfgsb>`
        - 'TNC'         :ref:`(see here) <optimize.minimize-tnc>`
        - 'COBYLA'      :ref:`(see here) <optimize.minimize-cobyla>`
        - 'SLSQP'       :ref:`(see here) <optimize.minimize-slsqp>`
        - 'dogleg'      :ref:`(see here) <optimize.minimize-dogleg>`
        - 'trust-ncg'   :ref:`(see here) <optimize.minimize-trustncg>`
        - custom - a callable object (added in version 0.14.0),
          see below for description.

#### Для методов 'Newton-CG', 'dogleg', 'trust-ncg' выводится ошибка ValueError: Jacobian is required for dogleg minimization

In [20]:
# чтобы не запускать все методы, создадим list с наименованиями
my_list = ['Nelder-Mead','Powell','CG','BFGS','L-BFGS-B','TNC','COBYLA','SLSQP']

# зададим мин количество выполнений функции как 1000
min_nfev = 1000

# и для каждого метода сравним nfev
for elem in my_list:
    x_min = optimize.minimize(f, [5, 5], method = elem)
    
    # отобразим все nfev
    print x_min.nfev,'\t', elem
    if x_min.nfev < min_nfev:
        min_nfev = x_min.nfev

print 'Наименьшее количество вычислений функции',' ', min_nfev

87 	Nelder-Mead
92 	Powell
20 	CG
16 	BFGS
9 	L-BFGS-B
22 	TNC
47 	COBYLA
9 	SLSQP
Наименьшее количество вычислений функции   9


## 2. Продвинутый уровень: изучаем изменения в документации sklearn

Установите себе самую свежую версию sklearn. В ней метод train_test_split должен быть в модуле model_selection, а не в cross_validation, как в старых версиях и в блокноте с лекции. Перепишите код с лекции так, чтобы вместо модуля sklearn.cross_validation он использовал sklearn.model_selection, и по-прежнему работал (продемонстрируйте это). Будьте внимательны к документации - сигнатура некоторых функций изменилась.

## 3. Сложный уровень: творческая часть

1. Заполните, пожалуйста, форму обратной связи по курсу: https://docs.google.com/forms/d/1aBPfORE8T3upInordGxPXZQiOPk4gFsIzvlimWerh7w Любые Ваши предложения могут быть очень ценны для нас, не стесняйтесь написать все, что думаете :)
1. Выберите любой модуль из не рассмотренных на последней лекции (можно взять любой из рекомендованных, можно любой на ваше усмотрение), напишите, зачем его используют и покажите несколько простых примеров его применения, предварительно разобравшись с ними в документации.